/**
 * Export content utility functions
 * Handles downloading generated content in various formats
 */

import type { ExportFormat } from '../components/export/ExportDropdown';

const formatFileNames: Record<ExportFormat, string> = {
  'client-email': 'client-email',
  'executive-summary': 'executive-summary',
  'investment-memo': 'investment-memo',
  'faq-sheet': 'faq-sheet',
  'meeting-prep': 'meeting-prep',
};

/**
 * Download content as a text file
 */
export function downloadAsText(
  content: string,
  format: ExportFormat,
  productName: string
): void {
  const fileName = `${productName.replace(/\s+/g, '-').toLowerCase()}-${formatFileNames[format]}-${Date.now()}.txt`;
  
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  URL.revokeObjectURL(url);
}

/**
 * Download content as a formatted document (future: Word/PDF)
 */
export function downloadAsDocument(
  content: string,
  format: ExportFormat,
  productName: string
): void {
  // For now, download as rich text
  // TODO: In future, convert to .docx or .pdf format
  const fileName = `${productName.replace(/\s+/g, '-').toLowerCase()}-${formatFileNames[format]}-${Date.now()}.txt`;
  
  // Add some basic formatting
  const formattedContent = `
═══════════════════════════════════════════════════════════════════
${productName.toUpperCase()}
${formatFileNames[format].replace(/-/g, ' ').toUpperCase()}
Generated: ${new Date().toLocaleString()}
═══════════════════════════════════════════════════════════════════

${content}

═══════════════════════════════════════════════════════════════════
Generated by Valura.ai | Structured Products Platform
This content was created using AI and should be reviewed before use.
═══════════════════════════════════════════════════════════════════
`.trim();

  const blob = new Blob([formattedContent], { type: 'text/plain; charset=utf-8' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  URL.revokeObjectURL(url);
}

